spring:
    cloud:
        bootstrap:
            enabled: true
    application:
        name: springbootdemo
        message: 'Message from application.yml'
        secret-message: ${secret:'Default Secret Message from application.yml'}