apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-kubernetes-access
automountServiceAccountToken: true

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-reader-binding
subjects:
- kind: ServiceAccount
  name: pod-kubernetes-access
  apiGroup: ""
roleRef:
  kind: Role
  name: kubernetes-reader
  apiGroup: ""