apiVersion: v1
kind: Service
metadata:
  labels:
    run: springbootdemo
  name: springbootdemo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: springbootdemo
  type: NodePort
status:
  loadBalancer: {}
